using System;
using System.Collections.Generic;

namespace DORv3.DAL.Models
{
    public partial class MasterFI
    {
        public int MasterFiId { get; set; }
        public int DORid { get; set; }
        public int Dealerid { get; set; }
        public string buyerlname { get; set; }
        public string buyerfname { get; set; }
        public string cobuyerlname { get; set; }
        public string cobuyerfname { get; set; }
        public string vehicle { get; set; }
        public Nullable<int> vehicleid { get; set; }
        public string vehicletype { get; set; }
        public Nullable<int> vehicletypeid { get; set; }
        public Nullable<int> businesssource { get; set; }
        public string otherbusinesssource { get; set; }
        public Nullable<int> salescategory { get; set; }
        public int status { get; set; }
        public string intent { get; set; }
        public string turnoption { get; set; }
        public Nullable<int> daysinstock { get; set; }
        public string dealnum { get; set; }
        public string stocknum { get; set; }
        public string make { get; set; }
        public string model { get; set; }
        public string makeother { get; set; }
        public string modelother { get; set; }
        public int year { get; set; }
        public int mileage { get; set; }
        public System.DateTime salesdate { get; set; }
        public Nullable<decimal> gross { get; set; }
        public decimal holdback { get; set; }
        public decimal payablegross { get; set; }
        public Nullable<decimal> frontendgross { get; set; }
        public bool trade1status { get; set; }
        public string trade1make { get; set; }
        public string trade1model { get; set; }
        public string trade1makeother { get; set; }
        public string trade1modelother { get; set; }
        public Nullable<int> trade1year { get; set; }
        public Nullable<int> trade1mileage { get; set; }
        public string trade1intent { get; set; }
        public string trade1title { get; set; }
        public string trade1lien { get; set; }
        public Nullable<decimal> trade1acv { get; set; }
        public Nullable<decimal> trade1payoff { get; set; }
        public Nullable<decimal> trade1equity { get; set; }
        public bool trade2status { get; set; }
        public string trade2make { get; set; }
        public string trade2model { get; set; }
        public string trade2makeother { get; set; }
        public string trade2modelother { get; set; }
        public Nullable<int> trade2year { get; set; }
        public Nullable<int> trade2mileage { get; set; }
        public string trade2intent { get; set; }
        public string trade2title { get; set; }
        public string trade2lien { get; set; }
        public Nullable<decimal> trade2acv { get; set; }
        public Nullable<decimal> trade2payoff { get; set; }
        public Nullable<decimal> trade2equity { get; set; }
        public Nullable<int> salesmanager { get; set; }
        public Nullable<int> salesperson1 { get; set; }
        public string salesperson1per { get; set; }
        public Nullable<int> salesperson2 { get; set; }
        public string salesperson2per { get; set; }
        public Nullable<int> salesperson3 { get; set; }
        public string salesperson3per { get; set; }
        public int fimanager { get; set; }
        public string fitype { get; set; }
        public string fipaymentin { get; set; }
        public string fipaymentout { get; set; }
        public string fitermin { get; set; }
        public string fitermout { get; set; }
        public Nullable<decimal> ficashdown { get; set; }
        public string lienholder { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<System.DateTime> delvdate { get; set; }
        public Nullable<int> gradecreditid { get; set; }
        public Nullable<int> gradecredit { get; set; }
        public Nullable<decimal> gap { get; set; }
        public Nullable<decimal> enviro { get; set; }
        public Nullable<decimal> etch { get; set; }
        public Nullable<decimal> dent { get; set; }
        public Nullable<decimal> tirewheel { get; set; }
        public Nullable<decimal> cl { get; set; }
        public Nullable<decimal> ah { get; set; }
        public Nullable<decimal> vsc { get; set; }
        public string vscoption { get; set; }
        public Nullable<decimal> TBD { get; set; }
        public Nullable<decimal> Maint { get; set; }
        public Nullable<decimal> finresv { get; set; }
        public Nullable<decimal> frontend { get; set; }
        public Nullable<decimal> backend { get; set; }
        public Nullable<decimal> totalgross { get; set; }
        public Nullable<int> creditscore { get; set; }
        public string datetoacct { get; set; }
        public string bookeddate { get; set; }
        public Nullable<System.DateTime> unwinddate { get; set; }
        public string datetotag { get; set; }
        public string datetobank { get; set; }
        public string datepaid { get; set; }
        public string sectrade { get; set; }
        public Nullable<decimal> amt_fin { get; set; }
        public Nullable<int> fintype { get; set; }
        public System.DateTime EnteredDt { get; set; }
        public System.DateTime UpdatedDt { get; set; }
    }
}
