//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DORv3.Domain
{
    using System;
    
    public partial class DOR1234Object
    {
        public string dealership { get; set; }
        public Nullable<int> dealer_id { get; set; }
        public Nullable<int> New_Vehicles { get; set; }
        public Nullable<int> Used_Vehicles { get; set; }
        public Nullable<int> Total_Units { get; set; }
        public Nullable<int> Cash_Deals { get; set; }
        public Nullable<double> Cash_Deals__ { get; set; }
        public Nullable<int> Conv_Deals { get; set; }
        public Nullable<double> Conv_Deals__ { get; set; }
        public Nullable<int> RBF_Deals { get; set; }
        public Nullable<double> RBF_Deals__ { get; set; }
        public Nullable<int> OSF_Deals { get; set; }
        public Nullable<double> OSF_Deals__ { get; set; }
        public Nullable<int> M_A_P_ { get; set; }
        public Nullable<int> TOTAL { get; set; }
        public Nullable<int> Travel { get; set; }
        public Nullable<double> Warranties__ { get; set; }
        public Nullable<int> Windsh { get; set; }
        public Nullable<double> Windsh__ { get; set; }
        public Nullable<int> Credit_Life { get; set; }
        public Nullable<double> Credit_Life__ { get; set; }
        public Nullable<int> A_H { get; set; }
        public Nullable<double> A_H__ { get; set; }
        public Nullable<int> ENV_ { get; set; }
        public Nullable<double> ENV___ { get; set; }
        public Nullable<int> ETCH { get; set; }
        public Nullable<double> ETCH__ { get; set; }
        public Nullable<int> GAP { get; set; }
        public Nullable<double> GAP__ { get; set; }
        public Nullable<int> KEY { get; set; }
        public Nullable<double> KEY__ { get; set; }
        public Nullable<double> CONV_Reserve { get; set; }
        public Nullable<double> CONV_Reserve_UNIT { get; set; }
        public Nullable<double> RBF_Reserve { get; set; }
        public Nullable<double> RBF_Reserve_UNIT { get; set; }
        public Nullable<int> Total_Reserve { get; set; }
        public Nullable<int> Total_Reserve_Per { get; set; }
        public Nullable<decimal> Cash_Income { get; set; }
        public Nullable<decimal> Conv_Income { get; set; }
        public Nullable<decimal> RBF_Income { get; set; }
        public Nullable<decimal> OSF_Income { get; set; }
        public Nullable<decimal> Total_Income { get; set; }
        public Nullable<int> Avg__Front { get; set; }
        public Nullable<int> Avg_F_I_Gross { get; set; }
        public Nullable<int> Avg_Front___Back { get; set; }
    }
}
