//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DORv3.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class DORProduct
    {
        public int DORProductId { get; set; }
        public Nullable<int> DORId { get; set; }
        public Nullable<int> OtherProductId { get; set; }
        public string PType { get; set; }
        public string AddDate { get; set; }
        public Nullable<decimal> PAmount { get; set; }
        public Nullable<int> Recap { get; set; }
        public string VSCOption { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string AddUser { get; set; }
        public string UpdUser { get; set; }
    }
}
