//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DORv3.Domain
{
    using System;
    
    public partial class FinanceRecapObject
    {
        public string dealer_name { get; set; }
        public Nullable<int> dealer_id { get; set; }
        public Nullable<int> cash_deals { get; set; }
        public Nullable<double> cash_deals_per { get; set; }
        public Nullable<decimal> per_deal_income_cash { get; set; }
        public Nullable<int> conv_deals { get; set; }
        public Nullable<double> conv_deals_per { get; set; }
        public Nullable<decimal> per_deal_income_conv { get; set; }
        public Nullable<int> RBF_deals { get; set; }
        public Nullable<double> RBF_deals_per { get; set; }
        public Nullable<decimal> per_deal_income_RBF { get; set; }
        public Nullable<int> OSF_deals { get; set; }
        public Nullable<double> OSF_deals_per { get; set; }
        public Nullable<decimal> per_deal_income_OSF { get; set; }
        public Nullable<int> warr { get; set; }
        public Nullable<double> warr_per { get; set; }
        public Nullable<decimal> per_warr_income { get; set; }
        public Nullable<int> dent { get; set; }
        public Nullable<double> dent_per { get; set; }
        public Nullable<decimal> per_dent_income { get; set; }
        public Nullable<int> maint { get; set; }
        public Nullable<double> maint_per { get; set; }
        public Nullable<decimal> per_maint_income { get; set; }
        public Nullable<int> cl { get; set; }
        public Nullable<double> cl_per { get; set; }
        public Nullable<decimal> per_cl_income { get; set; }
        public Nullable<int> ah { get; set; }
        public Nullable<double> ah_per { get; set; }
        public Nullable<decimal> per_ah_income { get; set; }
        public Nullable<int> env { get; set; }
        public Nullable<double> env_per { get; set; }
        public Nullable<decimal> per_env_income { get; set; }
        public Nullable<int> etch { get; set; }
        public Nullable<double> etch_per { get; set; }
        public Nullable<decimal> per_etch_income { get; set; }
        public Nullable<int> gap { get; set; }
        public Nullable<double> gap_per { get; set; }
        public Nullable<decimal> per_gap_income { get; set; }
        public Nullable<int> tw { get; set; }
        public Nullable<double> tw_per { get; set; }
        public Nullable<decimal> per_tw_income { get; set; }
        public Nullable<decimal> cash_tot { get; set; }
        public Nullable<decimal> conv_tot { get; set; }
        public Nullable<decimal> rbf_tot { get; set; }
        public Nullable<decimal> osf_tot { get; set; }
        public Nullable<decimal> tot_tot { get; set; }
        public Nullable<decimal> avg_fe { get; set; }
        public Nullable<decimal> avg_be { get; set; }
        public Nullable<decimal> avg_tot { get; set; }
        public Nullable<double> tot_vehicle { get; set; }
    }
}
