//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DORv3.Domain
{
    using System;
    
    public partial class NU_ReportObject
    {
        public string dealer_name { get; set; }
        public Nullable<int> dealer_id { get; set; }
        public Nullable<int> cash_deals_nv { get; set; }
        public Nullable<int> cash_deals_uv { get; set; }
        public Nullable<double> cash_deals_per_nv { get; set; }
        public Nullable<double> cash_deals_per_uv { get; set; }
        public Nullable<decimal> per_deal_income_cash_nv { get; set; }
        public Nullable<decimal> per_deal_income_cash_uv { get; set; }
        public Nullable<int> conv_deals_nv { get; set; }
        public Nullable<int> conv_deals_uv { get; set; }
        public Nullable<double> conv_deals_per_nv { get; set; }
        public Nullable<double> conv_deals_per_uv { get; set; }
        public Nullable<decimal> per_deal_income_conv_nv { get; set; }
        public Nullable<decimal> per_deal_income_conv_uv { get; set; }
        public Nullable<int> RBF_deals_nv { get; set; }
        public Nullable<int> RBF_deals_uv { get; set; }
        public Nullable<double> RBF_deals_per_nv { get; set; }
        public Nullable<double> RBF_deals_per_uv { get; set; }
        public Nullable<decimal> per_deal_income_RBF_nv { get; set; }
        public Nullable<decimal> per_deal_income_RBF_uv { get; set; }
        public Nullable<int> OSF_deals_nv { get; set; }
        public Nullable<int> OSF_deals_uv { get; set; }
        public Nullable<double> OSF_deals_per_nv { get; set; }
        public Nullable<double> OSF_deals_per_uv { get; set; }
        public Nullable<decimal> per_deal_income_OSF_nv { get; set; }
        public Nullable<decimal> per_deal_income_OSF_uv { get; set; }
        public Nullable<int> warr_nv { get; set; }
        public Nullable<int> warr_uv { get; set; }
        public Nullable<double> warr_per_nv { get; set; }
        public Nullable<double> warr_per_uv { get; set; }
        public Nullable<decimal> per_warr_income_nv { get; set; }
        public Nullable<decimal> per_warr_income_uv { get; set; }
        public Nullable<int> dent_nv { get; set; }
        public Nullable<int> dent_uv { get; set; }
        public Nullable<double> dent_per_nv { get; set; }
        public Nullable<double> dent_per_uv { get; set; }
        public Nullable<decimal> per_dent_income_nv { get; set; }
        public Nullable<decimal> per_dent_income_uv { get; set; }
        public Nullable<int> maint_nv { get; set; }
        public Nullable<int> maint_uv { get; set; }
        public Nullable<double> maint_per_nv { get; set; }
        public Nullable<double> maint_per_uv { get; set; }
        public Nullable<decimal> per_maint_income_nv { get; set; }
        public Nullable<decimal> per_maint_income_uv { get; set; }
        public Nullable<int> cl_nv { get; set; }
        public Nullable<int> cl_uv { get; set; }
        public Nullable<double> cl_per_nv { get; set; }
        public Nullable<double> cl_per_uv { get; set; }
        public Nullable<decimal> per_cl_income_nv { get; set; }
        public Nullable<decimal> per_cl_income_uv { get; set; }
        public Nullable<int> ah_nv { get; set; }
        public Nullable<int> ah_uv { get; set; }
        public Nullable<double> ah_per_nv { get; set; }
        public Nullable<double> ah_per_uv { get; set; }
        public Nullable<decimal> per_ah_income_nv { get; set; }
        public Nullable<decimal> per_ah_income_uv { get; set; }
        public Nullable<int> env_nv { get; set; }
        public Nullable<int> env_uv { get; set; }
        public Nullable<double> env_per_nv { get; set; }
        public Nullable<double> env_per_uv { get; set; }
        public Nullable<decimal> per_env_income_nv { get; set; }
        public Nullable<decimal> per_env_income_uv { get; set; }
        public Nullable<int> etch_nv { get; set; }
        public Nullable<int> etch_uv { get; set; }
        public Nullable<double> etch_per_nv { get; set; }
        public Nullable<double> etch_per_uv { get; set; }
        public Nullable<decimal> per_etch_income_nv { get; set; }
        public Nullable<decimal> per_etch_income_uv { get; set; }
        public Nullable<int> gap_nv { get; set; }
        public Nullable<int> gap_uv { get; set; }
        public Nullable<double> gap_per_nv { get; set; }
        public Nullable<double> gap_per_uv { get; set; }
        public Nullable<decimal> per_gap_income_nv { get; set; }
        public Nullable<decimal> per_gap_income_uv { get; set; }
        public Nullable<int> tw_nv { get; set; }
        public Nullable<int> tw_uv { get; set; }
        public Nullable<double> tw_per_nv { get; set; }
        public Nullable<double> tw_per_uv { get; set; }
        public Nullable<decimal> per_tw_income_nv { get; set; }
        public Nullable<decimal> per_tw_income_uv { get; set; }
        public Nullable<decimal> cash_tot_nv { get; set; }
        public Nullable<decimal> cash_tot_uv { get; set; }
        public Nullable<decimal> conv_tot_nv { get; set; }
        public Nullable<decimal> conv_tot_uv { get; set; }
        public Nullable<decimal> rbf_tot_nv { get; set; }
        public Nullable<decimal> rbf_tot_uv { get; set; }
        public Nullable<decimal> osf_tot_nv { get; set; }
        public Nullable<decimal> osf_tot_uv { get; set; }
        public Nullable<decimal> tot_tot_nv { get; set; }
        public Nullable<decimal> tot_tot_uv { get; set; }
        public Nullable<decimal> avg_fe_nv { get; set; }
        public Nullable<decimal> avg_fe_uv { get; set; }
        public Nullable<decimal> avg_be_nv { get; set; }
        public Nullable<decimal> avg_be_uv { get; set; }
        public Nullable<decimal> avg_tot_nv { get; set; }
        public Nullable<decimal> avg_tot_uv { get; set; }
        public Nullable<double> tot_vehicle_nv { get; set; }
        public Nullable<double> tot_vehicle_uv { get; set; }
    }
}
