//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DORv3.Domain
{
    using System;
    
    public partial class SalesboardObject
    {
        public int DealerId { get; set; }
        public string Dealership { get; set; }
        public System.DateTime DateOfSale { get; set; }
        public string DayOfTheWeek { get; set; }
        public Nullable<int> SellingDayNumber { get; set; }
        public Nullable<int> WeekNumber { get; set; }
        public Nullable<int> NewSalesCount { get; set; }
        public Nullable<int> UsedSalesCount { get; set; }
        public Nullable<int> UnwindSalesCount { get; set; }
        public string RGBColor { get; set; }
    }
}
