//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DORv3.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewUserRole
    {
        public string UserId { get; set; }
        public string UserName { get; set; }
        public Nullable<int> DealerShip { get; set; }
        public Nullable<int> RoleId { get; set; }
        public int SecurityId { get; set; }
        public Nullable<System.DateTime> DisableDate { get; set; }
    }
}
